# Generated by Django 3.2.3 on 2021-06-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='user_permissions',
        ),
    ]
