# Generated by Django 3.2.3 on 2021-06-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0002_auto_20210616_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customusers',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
