# Generated by Django 3.2.3 on 2021-06-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='myimages')),
            ],
        ),
    ]
