# Generated by Django 3.2.3 on 2021-06-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsforher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_ProductsForHer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.ImageField(upload_to='')),
                ('pic', models.ImageField(upload_to='sub_her')),
                ('productsforher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsforher')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.ImageField(upload_to='')),
                ('pic', models.ImageField(upload_to='sub_products')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
