# Generated by Django 3.2.3 on 2021-06-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_sub_productsforher_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
