# Generated by Django 3.2.3 on 2021-06-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210619_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_productsforher',
            name='custom_user',
        ),
        migrations.RemoveField(
            model_name='sub_productsforher',
            name='productsforher',
        ),
        migrations.RenameField(
            model_name='sub_products',
            old_name='products',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sub_products',
            name='custom_user',
        ),
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ProductsForHer',
        ),
        migrations.DeleteModel(
            name='Sub_ProductsForHer',
        ),
    ]
