# Generated by Django 3.2.3 on 2021-06-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_userproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
    ]
