# Generated by Django 3.2.3 on 2021-06-23 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_sub_products_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_products',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
