# Generated by Django 3.2.3 on 2021-06-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_sub_products_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProducts',
        ),
    ]
